# Python CircleCI 2.1 configuration file

version: 2.1
jobs: # a basic unit of work in a run
  build: # the main job to execute
    docker: # indicate that we are using the docker executor
      - image: 'circleci/python:latest' # Our selected version of Python

    working_directory: ~/repo

    steps: # a series of commands to run
      - checkout # pull down code from your version control system.
      - run:
          # create virtual environment and install dependencies
          name: Install Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - run:
          # run tests
          name: Run Tests
          command: |
            . venv/bin/activate
            pytest -v --cov=core

workflows:
  version: 2
  install_and_test:
    jobs:
      - build